[package]
name = "drivelist-rs"
version = "0.1.0"
authors = ["reido"]
edition = "2018"
links="drivelist"
build="build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
