#[repr(C)]
#[derive(Debug)]
pub struct DeviceDescriptor {
  pub enumerator: String,
  pub bus_type: String,
  pub bus_version: Option<String>,
  pub device: String,
  pub device_path: Option<String>,
  pub raw: String,
  pub description: String,
  pub error: Option<String>,
  pub size: u64,
  pub block_size: u32,
  pub logical_block_size: u32,
  pub mountpoints: Vec<String>,
  pub mountpoints_labels: Vec<String>,
  pub is_read_only: bool,
  pub is_system: bool,
  pub is_virtual: bool,
  pub is_removable: bool,
  pub is_card: bool,
  pub is_scsi: bool,
  pub is_usb: bool,
  pub is_uas: Option<bool>,
}
